title: "Roll Bot infra"
description: "Roll Bot + Monitoring"
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

groupings:
  - title: "General Configuration"
    visible: false
    variables:
      - tenancy_ocid
      - user_ocid
      - region
      - oci_private_key
      - fingerprint

  - title: "Optional Configuration"
    variables:
      - ssh_public_key

variables:
  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy"
    description: "The tenancy in which to create compute instance(s)"

  user_ocid:
    type: oci:identity:user:id
    required: true
    title: "User"
    description: "The user in which to create compute instance(s)"

  region:
    type: oci:identity:region
    required: true
    title: "Region"
    description: "The region in which to create compute instance(s)"

  oci_private_key:
    type: string
    required: true
    title: "OCI Private Key"
    description: "RSA key in PEM format"

  fingerprint:
    type: string
    required: true
    title: "Fingerprint"
    description: "Fingerprint of your RSA Public Key"
  
  ssh_public_key:
    type: string
    required: false
    title: "SSH Public Key"
    description: "The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH"

outputGroups:
  - title: "rollbot App details"
    outputs:
      - ${lb_public_url}
      - ${autonomous_database_password}
      - ${dev}
      - ${comments}

outputs:
  monitor_public_ip:
    type: string
    title: "Public IP of monitoring instance"
    visible: true

  rollbot_public_ip:
    type: string
    title: "Public IP of roll bot instance"
    visible: true
