[package]
name = "roll_bot"
version = "0.1.0"
authors = ["Sergei Gureev <bemyak@pm.me>"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
log = "0.4"
simplelog = { version = "0.8", features = ["test"] }
futures = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
serde_json = "1.0"
telegram-bot = { version = "0.7", features = ["rustls"], default-features = false }
ejdb = "0.4"
reqwest = { version = "0.10", features = ["json", "rustls-tls"], default-features = false }
rand = "0.7"
regex = "1"
hyper = "0.13"
hyper-proxy = "0.7"
hyper-rustls = "0.20"
lazy_static = "1.4"
