[package]
name = "roll_bot"
version = "0.1.0"
authors = ["Sergej Gureev <bemyak@gmail.com>"]

[profile.release]
lto = true
panic = 'abort'

[dependencies]
log = "0.4"
env_logger = "0.5"
futures = "0.1"
tokio-core = "0.1"
tokio = "0.1"
hyper-tls = "0.3"
serde_json = "1.0"
ejdb = { path = "../ejdb.rs" }
telegram-bot = { path = "../telegram-bot/lib" }


[dependencies.hyper]
version = "0.12"
default-features = false
