[package]
name = "roll_bot"
version = "0.1.0"
authors = ["Sergei Gureev <bemyak@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
log = "0.4"
simplelog = { version = "0.7", features = ["test"] }
futures = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
serde_json = "1.0"
telegram-bot = "0.7"
ejdb = "0.4"
reqwest = { version = "0.10", features = ["json"] }
rand = "0.7"
