[package]
authors = ["Sergei Gureev <bemyak@pm.me>"]
edition = "2021"
include = ["src/**/*", "LICENSE", "README.md"]
name  = "roll_bot"
version = "1.0.0"

[profile.release]
lto = "fat"
panic = 'abort'

[dependencies]
comfy-table    = "5.0.0"
ejdb           = "0.4.1"
futures        = { version = "0.3.17", default-features = false }
hyper          = { version = "0.14.14", default-features = false, features = ["server"] }
hyper-proxy    = { version = "0.9.1", default-features = false, features = ["rustls"] }
hyper-rustls   = "0.22.1"
lazy_static    = "1.4.0"
log            = { version = "0.4.14", default-features = false }
ordinal        = "0.2.3"
peg            = "0.7.0"
percent-encoding = "2.1.0"
prometheus     = { version = "0.13.0", default-features = false, features = ["process"] }
rand           = { version = "0.8.4", default-features = false }
regex          = { version = "1.5.4", default-features = false }
reqwest        = { version = "0.11.6", default-features = false, features = ["json", "rustls-tls"] }
serde          = "1.0.130"
serde_json     = { version = "1.0.68", default-features = false }
simplelog      = { version = "0.10.2", default-features = false }
simsearch      = "0.2.3"
# telegram-bot   = { git="https://github.com/telegram-rs/telegram-bot.git", branch="main", default-features=false, features=["rustls"] }
teloxide       = { path="../teloxide", default-features = false, features = ["rustls", "auto-send", "cache-me", "throttle"] }
thiserror      = "1.0.30"
tokio          = { version = "1.12.0", default-features = false, features = ["rt-multi-thread", "macros"] }
zalgo          = "0.2.0"

[dev-dependencies]
simplelog  = { version = "0.10.2", default-features = false, features = ["test"] }
tokio-test = "0.4.2"

[build-dependencies]
schemafy_lib = "0.6.0"

[features]
regenerate_types = []
