[package]
authors = ["Sergei Gureev <bemyak@pm.me>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]
name    = "roll_bot"
version = "1.0.0"

[profile.release]
lto   = true
panic = 'abort'

[dependencies]
comfy-table      = { version = "2.1" }
ejdb             = { version = "0.4" }
futures          = { version = "0.3", default-features = false }
hyper            = { version = "0.14", default-features = false, features = ["server"] }
hyper-proxy      = { version = "0.9", default-features = false, features = ["rustls"] }
hyper-rustls     = { version = "0.22" }
lazy_static      = { version = "1.4" }
log              = { version = "0.4", default-features = false }
ordinal          = { version = "0.2" }
peg              = { version = "0.7" }
percent-encoding = { version = "2.1" }
prometheus       = { version = "0.12", default-features = false, features = ["process"] }
rand             = { version = "0.8", default-features = false }
regex            = { version = "1", default-features = false }
reqwest          = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde            = { version = "1.0" }
serde_json       = { version = "1.0", default-features = false }
simplelog        = { version = "0.10", default-features = false }
simsearch        = { version = "0.2" }
telegram-bot     = { git = "https://github.com/bemyak/telegram-bot.git", default-features = false, features = ["rustls"] }
thiserror        = { version = "1.0" }
tokio            = { version = "1.5", default-features = false, features = ["rt-multi-thread", "macros"] }
zalgo            = { version = "0.2" }

[dev-dependencies]
simplelog  = { version = "0.10", default-features = false, features = ["test"] }
tokio-test = "0.4"
