{
 "title": "RollBot",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by(user_id) (message_counter))",
     "legendFormat": "Number of users"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up{}" }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(command) (message_counter)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Number of items in collection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collection_item_count", "legendFormat": "{{collection}}" }
   ]
  }
 ]
}