---

- name: Install firewalld
  apt:
    name: firewalld
    update_cache: yes
    state: present
  become: yes

- name: Apply firewall rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ allowed_ports }}"
  when: allowed_ports is defined
  become: yes
